[package]
name = "rust-colors"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
hex.workspace = true
proc-macro2.workspace = true
quote.workspace = true
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
