on:
  push:
    branches: [main]
jobs:
  cache-render-server:
    name: Cache / Render server
    runs-on: self-hosted
    steps:
      - uses: actions/cache/restore@v4
        id: lookup-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            render-server/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          lookup-only: true
      - name: Setup Rust
        if: steps.lookup-cache.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/checkout@v5
        if: steps.lookup-cache.outputs.cache-hit != 'true'
        with:
          sparse-checkout: render-server
      - uses: actions/cache@v4
        if: steps.lookup-cache.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            render-server/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Clippy
        if: steps.lookup-cache.outputs.cache-hit != 'true'
        run: cd render-server && cargo clippy --locked
