on:
  pull_request:
    branches: [main]
jobs:
  render-server:
    name: CI / Render server
    runs-on: self-hosted
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/checkout@v5
        with:
          sparse-checkout: render-server
      - name: Clippy
        run: cd render-server && cargo clippy --locked
      - name: Rustfmt
        run: cd render-server && rustfmt --check
