on:
  pull_request:
    branches: [main]
jobs:
  render-server:
    name: CI / Render server
    runs-on: self-hosted
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/checkout@v5
        with:
          sparse-checkout: render-server
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Clippy
        run: cd render-server && cargo clippy --locked
      - name: Rustfmt
        run: cd render-server && rustfmt --check
