name: CI
on:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.head_ref || github.ref_name }}-ci
  cancel-in-progress: true
jobs:
  js:
    name: JS
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "22.18.0"
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            package.json
            package-lock.json
            app
            contracts
            image-codec/pkg
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: NPM install
        run: npm ci
      - name: Test contracts
        run: cd contracts && npx blueprint build --all && npm test
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy, wasm-pack
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            Cargo.toml
            Cargo.lock
            render-server
            rust-colors
            image-codec
            palette.json
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Clippy
        run: cargo clippy --locked
      - name: Rustfmt
        run: cargo fmt --check
      - name: Run WasmPack
        run: cd ./image-codec && wasm-pack build --target web
      - name: Verify repo is clean
        run: |
          if ! git diff --quiet || ! git diff --cached --quiet; then
            exit 1
          fi
