name: Deploy
on:
  push:
    branches: [main]
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  fender-server:
    name: Render server
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKERHUB_AUTH_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            Cargo.toml
            Cargo.lock
            render-server
            rust-colors
            palette.json
            deploy
      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          file: ./deploy/render-server.Dockerfile
          build-args: APP_VERSION=${{ github.sha }}
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKERHUB_REGISTRY }}/canvas-render-server:latest
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_REGISTRY }}/canvas-render-server:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_REGISTRY }}/canvas-render-server:buildcache,mode=max
  app:
    name: App to GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            package.json
            package-lock.json
            contracts/package.json
            app
      - name: NPM install
        run: npm ci --workspace app
      - name: Build
        run: cd app && npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./app/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
