on:
  push:
    branches: [main]
jobs:
  fender-server:
    name: Deploy / Render server
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKERHUB_AUTH_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            render-server
            deploy
      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          file: ./deploy/render-server.Dockerfile
          build-args: APP_VERSION=${{ github.sha }}
          push: true
          tags: ${{ vars.DOCKERHUB_REGISTRY }}/canvas-render-server:latest
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_REGISTRY }}/canvas-render-server:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_REGISTRY }}/canvas-render-server:buildcache,mode=max